2025-04-29 13:12:33,970 - trading_system.exchange.binanceusdm_connector - WARNING - [binance_connector.py:170] - Lỗi headers trong response: 'dict' object has no attribute 'headers'
2025-04-29 13:12:33,971 - trading_system.exchange.binanceusdm_connector - WARNING - [binance_connector.py:171] - Đang thử phương pháp thay thế (lần 1/5)...
2025-04-29 13:12:33,972 - trading_system.exchange.binanceusdm_connector - INFO - [binance_connector.py:188] - Đã tải 4 thị trường mặc định để tạm thời sử dụng
2025-04-29 13:12:33,973 - trading_system.exchange.binanceusdm_connector - INFO - [generic_connector.py:90] - Đã khởi tạo kết nối binanceusdm mainnet
2025-04-29 13:12:33,974 - trading_system.exchange.binanceusdm_connector - INFO - [binance_connector.py:51] - Đã khởi tạo kết nối Binance Futures
2025-04-29 13:12:33,990 - trading_system.exchange.binanceusdm_connector - WARNING - [binance_connector.py:170] - Lỗi headers trong response: 'dict' object has no attribute 'headers'
2025-04-29 13:12:33,991 - trading_system.exchange.binanceusdm_connector - WARNING - [binance_connector.py:171] - Đang thử phương pháp thay thế (lần 1/5)...
2025-04-29 13:12:33,991 - trading_system.exchange.binanceusdm_connector - INFO - [binance_connector.py:188] - Đã tải 4 thị trường mặc định để tạm thời sử dụng
2025-04-29 13:12:33,992 - trading_system.exchange.binanceusdm_connector - INFO - [generic_connector.py:90] - Đã khởi tạo kết nối binanceusdm mainnet
2025-04-29 13:12:33,993 - trading_system.exchange.binanceusdm_connector - INFO - [binance_connector.py:51] - Đã khởi tạo kết nối Binance Futures
2025-04-29 13:12:33,994 - trading_system.exchange.binanceusdm_connector - INFO - [binance_connector.py:337] - Đã sử dụng thông tin 4 thị trường từ cache
2025-04-29 13:12:33,995 - trading_system.exchange.binanceusdm_connector - INFO - [generic_connector.py:671] - Đã khởi tạo thành công connector binanceusdm
2025-04-29 13:12:34,016 - trading_system.exchange.binanceusdm_connector - INFO - [generic_connector.py:682] - Đóng kết nối với binanceusdm
