2025-05-01 18:41:04,106 - trading_system.data_pipeline - ERROR - [data_pipeline.py:612] - Lỗi khi làm sạch dữ liệu cho BTC/USDT: local variable 'outlier_cols' referenced before assignment
2025-05-01 18:41:04,142 - trading_system.data_pipeline - ERROR - [data_pipeline.py:612] - Lỗi khi làm sạch dữ liệu cho ETH/USDT: local variable 'outlier_cols' referenced before assignment
